// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/app_setting_entity.dart';
import 'data/models/bill_reminder_entity.dart';
import 'data/models/khata_contact_entity.dart';
import 'data/models/khata_entry_entity.dart';
import 'data/models/transaction_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5579513230018215064),
    name: 'BillReminderEntity',
    lastPropertyId: const obx_int.IdUid(9, 4567318457456961924),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1646954864954897948),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4040479769794883911),
        name: 'uid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 1241367880183810384),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6839329035114131065),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2800818746501707384),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7996067479029655202),
        name: 'dueDate',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(2, 3624657269601512892),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7400883897148399453),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4557647017582631029),
        name: 'isPaid',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7991056193354628222),
        name: 'recurrence',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4567318457456961924),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6319392063145742835),
    name: 'KhataContactEntity',
    lastPropertyId: const obx_int.IdUid(6, 648745224205944255),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8373449443008316482),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6042571345203459542),
        name: 'uid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 111896912165150009),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4555141118253808330),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4959036579307854363),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2944858499332187846),
        name: 'createdAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 648745224205944255),
        name: 'avatarColorValue',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'entries',
        srcEntity: 'KhataEntryEntity',
        srcField: 'contact',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 9025544644016184217),
    name: 'KhataEntryEntity',
    lastPropertyId: const obx_int.IdUid(11, 4213167380193738433),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3073571744691332211),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6210972413327320833),
        name: 'uid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 4071652042096998255),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4259362243929400723),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1208810932975895528),
        name: 'type',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 7945428052368560305),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4402711665916701680),
        name: 'date',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(6, 6958395748022234296),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 32800847761894955),
        name: 'dueDate',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2354186064478360054),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3441387401805460703),
        name: 'isSettled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5393403344436247786),
        name: 'contactId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 2499354298945978445),
        relationField: 'contact',
        relationTarget: 'KhataContactEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4167654721294079963),
        name: 'transactionId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(14, 8189672903923528940),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4213167380193738433),
        name: 'platform',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5354481342646244362),
    name: 'TransactionEntity',
    lastPropertyId: const obx_int.IdUid(15, 3852618108970050335),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8542978380315412299),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3509368018389350199),
        name: 'uid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 5268145437566814250),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4485647560969961350),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 147241002099784381),
        name: 'type',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(9, 6142940680918494830),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6917243221425208558),
        name: 'category',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(10, 450158500652473866),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5402160090082300294),
        name: 'merchant',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7200905912957904680),
        name: 'platform',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(11, 5245493806902785004),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4548301563164315507),
        name: 'transactionId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(12, 5254394497647512987),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3730046870293130857),
        name: 'accountOrCard',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4203978725881757306),
        name: 'date',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(13, 4383274247065485941),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7699051939632215261),
        name: 'rawSms',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2976383419395817951),
        name: 'balanceAfter',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7657578494166693516),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5688478110731555722),
        name: 'isAutomated',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 3852618108970050335),
        name: 'isIgnored',
        type: 1,
        flags: 8,
        indexId: const obx_int.IdUid(15, 8882575473084078892),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 4428729137688253300),
    name: 'AppSettingEntity',
    lastPropertyId: const obx_int.IdUid(3, 6050237961683151311),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6607417577973974692),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 545892116628955912),
        name: 'key',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(16, 8174359078345522723),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6050237961683151311),
        name: 'value',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 4428729137688253300),
    lastIndexId: const obx_int.IdUid(16, 8174359078345522723),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BillReminderEntity: obx_int.EntityDefinition<BillReminderEntity>(
      model: _entities[0],
      toOneRelations: (BillReminderEntity object) => [],
      toManyRelations: (BillReminderEntity object) => {},
      getId: (BillReminderEntity object) => object.id,
      setId: (BillReminderEntity object, int id) {
        object.id = id;
      },
      objectToFB: (BillReminderEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final titleOffset = fbb.writeString(object.title);
        final categoryOffset = fbb.writeString(object.category);
        final recurrenceOffset = fbb.writeString(object.recurrence);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addFloat64(3, object.amount);
        fbb.addInt64(4, object.dueDate);
        fbb.addOffset(5, categoryOffset);
        fbb.addBool(6, object.isPaid);
        fbb.addOffset(7, recurrenceOffset);
        fbb.addOffset(8, notesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final dueDateParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final isPaidParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final recurrenceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = BillReminderEntity(
          id: idParam,
          uid: uidParam,
          title: titleParam,
          amount: amountParam,
          dueDate: dueDateParam,
          category: categoryParam,
          isPaid: isPaidParam,
          recurrence: recurrenceParam,
          notes: notesParam,
        );

        return object;
      },
    ),
    KhataContactEntity: obx_int.EntityDefinition<KhataContactEntity>(
      model: _entities[1],
      toOneRelations: (KhataContactEntity object) => [],
      toManyRelations: (KhataContactEntity object) => {
        obx_int.RelInfo<KhataEntryEntity>.toOneBacklink(
          9,
          object.id,
          (KhataEntryEntity srcObject) => srcObject.contact,
        ): object.entries,
      },
      getId: (KhataContactEntity object) => object.id,
      setId: (KhataContactEntity object, int id) {
        object.id = id;
      },
      objectToFB: (KhataContactEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final nameOffset = fbb.writeString(object.name);
        final phoneNumberOffset = object.phoneNumber == null
            ? null
            : fbb.writeString(object.phoneNumber!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, phoneNumberOffset);
        fbb.addInt64(4, object.createdAt);
        fbb.addInt64(5, object.avatarColorValue);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final avatarColorValueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = KhataContactEntity(
          id: idParam,
          uid: uidParam,
          name: nameParam,
          phoneNumber: phoneNumberParam,
          createdAt: createdAtParam,
          avatarColorValue: avatarColorValueParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<KhataContactEntity>(
          object.entries,
          store,
          obx_int.RelInfo<KhataEntryEntity>.toOneBacklink(
            9,
            object.id,
            (KhataEntryEntity srcObject) => srcObject.contact,
          ),
        );
        return object;
      },
    ),
    KhataEntryEntity: obx_int.EntityDefinition<KhataEntryEntity>(
      model: _entities[2],
      toOneRelations: (KhataEntryEntity object) => [object.contact],
      toManyRelations: (KhataEntryEntity object) => {},
      getId: (KhataEntryEntity object) => object.id,
      setId: (KhataEntryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (KhataEntryEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final typeOffset = fbb.writeString(object.type);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final transactionIdOffset = object.transactionId == null
            ? null
            : fbb.writeString(object.transactionId!);
        final platformOffset = object.platform == null
            ? null
            : fbb.writeString(object.platform!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addOffset(3, typeOffset);
        fbb.addInt64(4, object.date);
        fbb.addInt64(5, object.dueDate);
        fbb.addOffset(6, notesOffset);
        fbb.addBool(7, object.isSettled);
        fbb.addInt64(8, object.contact.targetId);
        fbb.addOffset(9, transactionIdOffset);
        fbb.addOffset(10, platformOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final dateParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final dueDateParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final transactionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final platformParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final isSettledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = KhataEntryEntity(
          id: idParam,
          uid: uidParam,
          amount: amountParam,
          type: typeParam,
          date: dateParam,
          dueDate: dueDateParam,
          transactionId: transactionIdParam,
          platform: platformParam,
          notes: notesParam,
          isSettled: isSettledParam,
        );
        object.contact.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.contact.attach(store);
        return object;
      },
    ),
    TransactionEntity: obx_int.EntityDefinition<TransactionEntity>(
      model: _entities[3],
      toOneRelations: (TransactionEntity object) => [],
      toManyRelations: (TransactionEntity object) => {},
      getId: (TransactionEntity object) => object.id,
      setId: (TransactionEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TransactionEntity object, fb.Builder fbb) {
        final uidOffset = fbb.writeString(object.uid);
        final typeOffset = fbb.writeString(object.type);
        final categoryOffset = fbb.writeString(object.category);
        final merchantOffset = object.merchant == null
            ? null
            : fbb.writeString(object.merchant!);
        final platformOffset = object.platform == null
            ? null
            : fbb.writeString(object.platform!);
        final transactionIdOffset = object.transactionId == null
            ? null
            : fbb.writeString(object.transactionId!);
        final accountOrCardOffset = object.accountOrCard == null
            ? null
            : fbb.writeString(object.accountOrCard!);
        final rawSmsOffset = object.rawSms == null
            ? null
            : fbb.writeString(object.rawSms!);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uidOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addOffset(3, typeOffset);
        fbb.addOffset(4, categoryOffset);
        fbb.addOffset(5, merchantOffset);
        fbb.addOffset(6, platformOffset);
        fbb.addOffset(7, transactionIdOffset);
        fbb.addOffset(8, accountOrCardOffset);
        fbb.addInt64(9, object.date);
        fbb.addOffset(10, rawSmsOffset);
        fbb.addFloat64(11, object.balanceAfter);
        fbb.addOffset(12, notesOffset);
        fbb.addBool(13, object.isAutomated);
        fbb.addBool(14, object.isIgnored);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final merchantParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final platformParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final transactionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final accountOrCardParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final dateParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final rawSmsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final balanceAfterParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final isAutomatedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final isIgnoredParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          32,
          false,
        );
        final object = TransactionEntity(
          id: idParam,
          uid: uidParam,
          amount: amountParam,
          type: typeParam,
          category: categoryParam,
          merchant: merchantParam,
          platform: platformParam,
          transactionId: transactionIdParam,
          accountOrCard: accountOrCardParam,
          date: dateParam,
          rawSms: rawSmsParam,
          balanceAfter: balanceAfterParam,
          notes: notesParam,
          isAutomated: isAutomatedParam,
          isIgnored: isIgnoredParam,
        );

        return object;
      },
    ),
    AppSettingEntity: obx_int.EntityDefinition<AppSettingEntity>(
      model: _entities[4],
      toOneRelations: (AppSettingEntity object) => [],
      toManyRelations: (AppSettingEntity object) => {},
      getId: (AppSettingEntity object) => object.id,
      setId: (AppSettingEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AppSettingEntity object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, valueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = AppSettingEntity(
          id: idParam,
          key: keyParam,
          value: valueParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BillReminderEntity] entity fields to define ObjectBox queries.
class BillReminderEntity_ {
  /// See [BillReminderEntity.id].
  static final id = obx.QueryIntegerProperty<BillReminderEntity>(
    _entities[0].properties[0],
  );

  /// See [BillReminderEntity.uid].
  static final uid = obx.QueryStringProperty<BillReminderEntity>(
    _entities[0].properties[1],
  );

  /// See [BillReminderEntity.title].
  static final title = obx.QueryStringProperty<BillReminderEntity>(
    _entities[0].properties[2],
  );

  /// See [BillReminderEntity.amount].
  static final amount = obx.QueryDoubleProperty<BillReminderEntity>(
    _entities[0].properties[3],
  );

  /// See [BillReminderEntity.dueDate].
  static final dueDate = obx.QueryIntegerProperty<BillReminderEntity>(
    _entities[0].properties[4],
  );

  /// See [BillReminderEntity.category].
  static final category = obx.QueryStringProperty<BillReminderEntity>(
    _entities[0].properties[5],
  );

  /// See [BillReminderEntity.isPaid].
  static final isPaid = obx.QueryBooleanProperty<BillReminderEntity>(
    _entities[0].properties[6],
  );

  /// See [BillReminderEntity.recurrence].
  static final recurrence = obx.QueryStringProperty<BillReminderEntity>(
    _entities[0].properties[7],
  );

  /// See [BillReminderEntity.notes].
  static final notes = obx.QueryStringProperty<BillReminderEntity>(
    _entities[0].properties[8],
  );
}

/// [KhataContactEntity] entity fields to define ObjectBox queries.
class KhataContactEntity_ {
  /// See [KhataContactEntity.id].
  static final id = obx.QueryIntegerProperty<KhataContactEntity>(
    _entities[1].properties[0],
  );

  /// See [KhataContactEntity.uid].
  static final uid = obx.QueryStringProperty<KhataContactEntity>(
    _entities[1].properties[1],
  );

  /// See [KhataContactEntity.name].
  static final name = obx.QueryStringProperty<KhataContactEntity>(
    _entities[1].properties[2],
  );

  /// See [KhataContactEntity.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<KhataContactEntity>(
    _entities[1].properties[3],
  );

  /// See [KhataContactEntity.createdAt].
  static final createdAt = obx.QueryIntegerProperty<KhataContactEntity>(
    _entities[1].properties[4],
  );

  /// See [KhataContactEntity.avatarColorValue].
  static final avatarColorValue = obx.QueryIntegerProperty<KhataContactEntity>(
    _entities[1].properties[5],
  );

  /// see [KhataContactEntity.entries]
  static final entries =
      obx.QueryBacklinkToMany<KhataEntryEntity, KhataContactEntity>(
        KhataEntryEntity_.contact,
      );
}

/// [KhataEntryEntity] entity fields to define ObjectBox queries.
class KhataEntryEntity_ {
  /// See [KhataEntryEntity.id].
  static final id = obx.QueryIntegerProperty<KhataEntryEntity>(
    _entities[2].properties[0],
  );

  /// See [KhataEntryEntity.uid].
  static final uid = obx.QueryStringProperty<KhataEntryEntity>(
    _entities[2].properties[1],
  );

  /// See [KhataEntryEntity.amount].
  static final amount = obx.QueryDoubleProperty<KhataEntryEntity>(
    _entities[2].properties[2],
  );

  /// See [KhataEntryEntity.type].
  static final type = obx.QueryStringProperty<KhataEntryEntity>(
    _entities[2].properties[3],
  );

  /// See [KhataEntryEntity.date].
  static final date = obx.QueryIntegerProperty<KhataEntryEntity>(
    _entities[2].properties[4],
  );

  /// See [KhataEntryEntity.dueDate].
  static final dueDate = obx.QueryIntegerProperty<KhataEntryEntity>(
    _entities[2].properties[5],
  );

  /// See [KhataEntryEntity.notes].
  static final notes = obx.QueryStringProperty<KhataEntryEntity>(
    _entities[2].properties[6],
  );

  /// See [KhataEntryEntity.isSettled].
  static final isSettled = obx.QueryBooleanProperty<KhataEntryEntity>(
    _entities[2].properties[7],
  );

  /// See [KhataEntryEntity.contact].
  static final contact =
      obx.QueryRelationToOne<KhataEntryEntity, KhataContactEntity>(
        _entities[2].properties[8],
      );

  /// See [KhataEntryEntity.transactionId].
  static final transactionId = obx.QueryStringProperty<KhataEntryEntity>(
    _entities[2].properties[9],
  );

  /// See [KhataEntryEntity.platform].
  static final platform = obx.QueryStringProperty<KhataEntryEntity>(
    _entities[2].properties[10],
  );
}

/// [TransactionEntity] entity fields to define ObjectBox queries.
class TransactionEntity_ {
  /// See [TransactionEntity.id].
  static final id = obx.QueryIntegerProperty<TransactionEntity>(
    _entities[3].properties[0],
  );

  /// See [TransactionEntity.uid].
  static final uid = obx.QueryStringProperty<TransactionEntity>(
    _entities[3].properties[1],
  );

  /// See [TransactionEntity.amount].
  static final amount = obx.QueryDoubleProperty<TransactionEntity>(
    _entities[3].properties[2],
  );

  /// See [TransactionEntity.type].
  static final type = obx.QueryStringProperty<TransactionEntity>(
    _entities[3].properties[3],
  );

  /// See [TransactionEntity.category].
  static final category = obx.QueryStringProperty<TransactionEntity>(
    _entities[3].properties[4],
  );

  /// See [TransactionEntity.merchant].
  static final merchant = obx.QueryStringProperty<TransactionEntity>(
    _entities[3].properties[5],
  );

  /// See [TransactionEntity.platform].
  static final platform = obx.QueryStringProperty<TransactionEntity>(
    _entities[3].properties[6],
  );

  /// See [TransactionEntity.transactionId].
  static final transactionId = obx.QueryStringProperty<TransactionEntity>(
    _entities[3].properties[7],
  );

  /// See [TransactionEntity.accountOrCard].
  static final accountOrCard = obx.QueryStringProperty<TransactionEntity>(
    _entities[3].properties[8],
  );

  /// See [TransactionEntity.date].
  static final date = obx.QueryIntegerProperty<TransactionEntity>(
    _entities[3].properties[9],
  );

  /// See [TransactionEntity.rawSms].
  static final rawSms = obx.QueryStringProperty<TransactionEntity>(
    _entities[3].properties[10],
  );

  /// See [TransactionEntity.balanceAfter].
  static final balanceAfter = obx.QueryDoubleProperty<TransactionEntity>(
    _entities[3].properties[11],
  );

  /// See [TransactionEntity.notes].
  static final notes = obx.QueryStringProperty<TransactionEntity>(
    _entities[3].properties[12],
  );

  /// See [TransactionEntity.isAutomated].
  static final isAutomated = obx.QueryBooleanProperty<TransactionEntity>(
    _entities[3].properties[13],
  );

  /// See [TransactionEntity.isIgnored].
  static final isIgnored = obx.QueryBooleanProperty<TransactionEntity>(
    _entities[3].properties[14],
  );
}

/// [AppSettingEntity] entity fields to define ObjectBox queries.
class AppSettingEntity_ {
  /// See [AppSettingEntity.id].
  static final id = obx.QueryIntegerProperty<AppSettingEntity>(
    _entities[4].properties[0],
  );

  /// See [AppSettingEntity.key].
  static final key = obx.QueryStringProperty<AppSettingEntity>(
    _entities[4].properties[1],
  );

  /// See [AppSettingEntity.value].
  static final value = obx.QueryStringProperty<AppSettingEntity>(
    _entities[4].properties[2],
  );
}
