import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

/// Comprehensive multi-language localization manager
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    // English
    'en': {
      'app_title': 'SpendWise',
      'dashboard': 'Dashboard',
      'transactions': 'Transactions',
      'khata': 'KhataBook',
      'analytics': 'Analytics',
      'reminders': 'Reminders',
      'total_balance': 'Total Balance',
      'total_income': 'Total Income',
      'total_expense': 'Total Expense',
      'today_spend': "Today's Spend",
      'monthly_budget': 'Monthly Budget',
      'recent_transactions': 'Recent Transactions',
      'view_all': 'View All',
      'sync_sms': 'Sync SMS',
      'add_expense': 'Add Expense',
      'add_income': 'Add Income',
      'this_month': 'This Month',
      'last_month': 'Last Month',
      'all_time': 'All Time',
      'custom_range': 'Custom Range',
      'all_transactions': 'All Transactions',
      'search_transactions': 'Search transactions...',
      'filter': 'Filter',
      'income': 'Income',
      'expense': 'Expense',
      'all': 'All',
      'delete': 'Delete',
      'save': 'Save',
      'cancel': 'Cancel',
      'khata_ledger': 'Khata Ledger',
      'you_will_receive': 'You will receive',
      'you_will_give': 'You will give',
      'add_customer': 'Add Customer / Friend',
      'you_gave': 'You Gave (Maine Diye)',
      'you_got': 'You Got (Mujhe Mile)',
      'settle': 'Settle Account',
      'whatsapp_reminder': 'WhatsApp Reminder',
      'linked_transaction': 'Linked Transaction',
      'bill_reminders': 'Bill Reminders',
      'upcoming': 'Upcoming',
      'overdue': 'Overdue',
      'paid': 'Paid',
      'mark_paid': 'Mark Paid',
      'language': 'Language',
      'select_language': 'Select Language',
      'export_pdf': 'Export PDF Statement',
      'account_settled': 'Account Settled',
      'no_transactions': 'No transactions found',
      'no_entries': 'No entries yet',
    },

    // Hindi (हिन्दी)
    'hi': {
      'app_title': 'स्पेंडवाइज',
      'dashboard': 'डैशबोर्ड',
      'transactions': 'लेन-देन',
      'khata': 'खाताबुक',
      'analytics': 'एनालिटिक्स',
      'reminders': 'रिमाइंडर',
      'total_balance': 'कुल बैलेंस',
      'total_income': 'कुल आय',
      'total_expense': 'कुल खर्च',
      'today_spend': 'आज का खर्च',
      'monthly_budget': 'मासिक बजट',
      'recent_transactions': 'हालिया लेन-देन',
      'view_all': 'सभी देखें',
      'sync_sms': 'एसएमएस सिंक करें',
      'add_expense': 'खर्च जोड़ें',
      'add_income': 'आय जोड़ें',
      'this_month': 'इस महीने',
      'last_month': 'पिछले महीने',
      'all_time': 'सभी समय',
      'custom_range': 'कस्टम अवधि',
      'all_transactions': 'सभी लेन-देन',
      'search_transactions': 'लेन-देन खोजें...',
      'filter': 'फ़िल्टर',
      'income': 'आय (क्रेडिट)',
      'expense': 'खर्च (डेबिट)',
      'all': 'सभी',
      'delete': 'हटाएं',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'khata_ledger': 'खाता लेजर',
      'you_will_receive': 'आपको मिलेंगे',
      'you_will_give': 'आपको देने हैं',
      'add_customer': 'ग्राहक / मित्र जोड़ें',
      'you_gave': 'मैंने दिए (Gave)',
      'you_got': 'मुझे मिले (Got)',
      'settle': 'खाता चुकता करें',
      'whatsapp_reminder': 'व्हाट्सएप रिमाइंडर',
      'linked_transaction': 'लिंक किया गया लेन-देन',
      'bill_reminders': 'बिल रिमाइंडर',
      'upcoming': 'आगामी',
      'overdue': 'बकाया (Overdue)',
      'paid': 'भुगतान किया गया',
      'mark_paid': 'भुगतान चिह्नित करें',
      'language': 'भाषा',
      'select_language': 'भाषा चुनें',
      'export_pdf': 'पीडीएफ स्टेटमेंट डाउनलोड',
      'account_settled': 'खाता चुकता हो चुका है',
      'no_transactions': 'कोई लेन-देन नहीं मिला',
      'no_entries': 'अभी तक कोई प्रविष्टि नहीं',
    },

    // Bengali (বাংলা)
    'bn': {
      'app_title': 'স্পেন্ডওয়াইজ',
      'dashboard': 'ড্যাশবোর্ড',
      'transactions': 'লেনদেন',
      'khata': 'খাতাবই',
      'analytics': 'বিশ্লেষণ',
      'reminders': 'স্মারক',
      'total_balance': 'মোট ব্যালেন্স',
      'total_income': 'মোট আয়',
      'total_expense': 'মোট ব্যয়',
      'today_spend': 'আজকের ব্যয়',
      'monthly_budget': 'মাসিক বাজেট',
      'recent_transactions': 'সাম্প্রতিক লেনদেন',
      'view_all': 'সব দেখুন',
      'sync_sms': 'এসএমএস সিঙ্ক করুন',
      'add_expense': 'ব্যয় যোগ করুন',
      'add_income': 'আয় যোগ করুন',
      'this_month': 'এই মাস',
      'last_month': 'গত মাস',
      'all_time': 'সর্বকালীন',
      'custom_range': 'কাস্টম রেঞ্জ',
      'all_transactions': 'সমস্ত লেনদেন',
      'search_transactions': 'লেনদেন অনুসন্ধান করুন...',
      'filter': 'ফিল্টার',
      'income': 'আয়',
      'expense': 'ব্যয়',
      'all': 'সব',
      'delete': 'মুছুন',
      'save': 'সংরক্ষণ করুন',
      'cancel': 'বাতিল করুন',
      'khata_ledger': 'খাতা খতিয়ান',
      'you_will_receive': 'আপনি পাবেন',
      'you_will_give': 'আপনি দেবেন',
      'add_customer': 'গ্রাহক যোগ করুন',
      'you_gave': 'দিয়েছেন',
      'you_got': 'পেয়েছেন',
      'settle': 'হিসাব নিষ্পত্তি',
      'whatsapp_reminder': 'হোয়াটসঅ্যাপ স্মারক',
      'linked_transaction': 'সংযুক্ত লেনদেন',
      'bill_reminders': 'বিল রিমাইন্ডার',
      'upcoming': 'আসন্ন',
      'overdue': 'বকেয়া',
      'paid': 'পরিশোধিত',
      'mark_paid': 'পরিশোধ চিহ্নিত করুন',
      'language': 'ভাষা',
      'select_language': 'ভাষা নির্বাচন করুন',
      'export_pdf': 'পিডিএফ স্টেটমেন্ট এক্সপোর্ট',
      'account_settled': 'হিসাব নিষ্পত্তি হয়েছে',
      'no_transactions': 'কোনো লেনদেন পাওয়া যায়নি',
      'no_entries': 'এখনও কোনো এন্ট্রি নেই',
    },

    // Urdu (اردو) - RTL
    'ur': {
      'app_title': 'اسپینڈ وائز',
      'dashboard': 'ڈیش بورڈ',
      'transactions': 'لین دین',
      'khata': 'کھاتہ بک',
      'analytics': 'تجزیہ',
      'reminders': 'یاد دہانی',
      'total_balance': 'کل بیلنس',
      'total_income': 'کل آمدنی',
      'total_expense': 'کل خرچ',
      'today_spend': 'آج کا خرچ',
      'monthly_budget': 'ماہانہ بجٹ',
      'recent_transactions': 'حالیہ لین دین',
      'view_all': 'سب دیکھیں',
      'sync_sms': 'ایس ایم ایس مطابقت',
      'add_expense': 'خرچ شامل کریں',
      'add_income': 'آمدنی شامل کریں',
      'this_month': 'اس مہینے',
      'last_month': 'پچھلے مہینے',
      'all_time': 'ہر وقت',
      'custom_range': 'اپنی مرضی کی مدت',
      'all_transactions': 'تمام لین دین',
      'search_transactions': 'لین دین تلاش کریں...',
      'filter': 'فلٹر',
      'income': 'آمدنی',
      'expense': 'خرچ',
      'all': 'سب',
      'delete': 'حذف کریں',
      'save': 'محفوظ کریں',
      'cancel': 'منسوخ کریں',
      'khata_ledger': 'کھاتہ لیجر',
      'you_will_receive': 'آپ وصول کریں گے',
      'you_will_give': 'آپ کو ادا کرنا ہوگا',
      'add_customer': 'کسٹمر شامل کریں',
      'you_gave': 'آپ نے دیے',
      'you_got': 'آپ کو ملے',
      'settle': 'کھاتہ چکتا کریں',
      'whatsapp_reminder': 'واٹس ایپ یاد دہانی',
      'linked_transaction': 'منسلک لین دین',
      'bill_reminders': 'بل یاد دہانیاں',
      'upcoming': 'آئندہ',
      'overdue': 'واجب الادا',
      'paid': 'ادا شدہ',
      'mark_paid': 'ادا شدہ نشان لگائیں',
      'language': 'زبان',
      'select_language': 'زبان منتخب کریں',
      'export_pdf': 'پی ڈی ایف اسٹیٹمنٹ نکالیں',
      'account_settled': 'کھاتہ چکتا ہو گیا ہے',
      'no_transactions': 'کوئی لین دین نہیں ملا',
      'no_entries': 'ابھی تک کوئی اندراج نہیں',
    },

    // Arabic (العربية) - RTL
    'ar': {
      'app_title': 'سبيند وايز',
      'dashboard': 'لوحة القيادة',
      'transactions': 'المعاملات',
      'khata': 'دفتر الحسابات',
      'analytics': 'التحليلات',
      'reminders': 'التذكيرات',
      'total_balance': 'إجمالي الرصيد',
      'total_income': 'إجمالي الدخل',
      'total_expense': 'إجمالي المصروفات',
      'today_spend': 'إنفاق اليوم',
      'monthly_budget': 'الميزانية الشهرية',
      'recent_transactions': 'أحدث المعاملات',
      'view_all': 'عرض الكل',
      'sync_sms': 'مزامنة الرسائل',
      'add_expense': 'إضافة مصروف',
      'add_income': 'إضافة دخل',
      'this_month': 'هذا الشهر',
      'last_month': 'الشهر الماضي',
      'all_time': 'كل الأوقات',
      'custom_range': 'نطاق مخصص',
      'all_transactions': 'جميع المعاملات',
      'search_transactions': 'بحث في المعاملات...',
      'filter': 'تصفية',
      'income': 'دخل',
      'expense': 'مصروف',
      'all': 'الكل',
      'delete': 'حذف',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'khata_ledger': 'سجل الحسابات',
      'you_will_receive': 'ستستلم',
      'you_will_give': 'ستدفع',
      'add_customer': 'إضافة عميل',
      'you_gave': 'أعطيت',
      'you_got': 'استلمت',
      'settle': 'تسوية الحساب',
      'whatsapp_reminder': 'تذكير واتساب',
      'linked_transaction': 'معاملة مرتبطة',
      'bill_reminders': 'تذكيرات الفواتير',
      'upcoming': 'قادم',
      'overdue': 'متأخر',
      'paid': 'مدفوع',
      'mark_paid': 'تحديد كمدفوع',
      'language': 'اللغة',
      'select_language': 'اختر اللغة',
      'export_pdf': 'تصدير كشف حساب PDF',
      'account_settled': 'تمت تسوية الحساب',
      'no_transactions': 'لم يتم العثور على معاملات',
      'no_entries': 'لا توجد قيود حتى الآن',
    },

    // Kannada (ಕನ್ನಡ)
    'kn': {
      'app_title': 'ಸ್ಪೆಂಡ್‌ವೈಸ್',
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'transactions': 'ವಹಿವಾಟುಗಳು',
      'khata': 'ಖಾತಾಬುಕ್',
      'analytics': 'ವಿಶ್ಲೇಷಣೆ',
      'reminders': 'ಜ್ಞಾಪನೆಗಳು',
      'total_balance': 'ಒಟ್ಟು ಬ್ಯಾಲೆನ್ಸ್',
      'total_income': 'ಒಟ್ಟು ಆದಾಯ',
      'total_expense': 'ಒಟ್ಟು ವೆಚ್ಚ',
      'today_spend': 'ಇಂದಿನ ಖರ್ಚು',
      'monthly_budget': 'ಮಾಸಿಕ ಬಜೆಟ್',
      'recent_transactions': 'ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು',
      'view_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      'sync_sms': 'ಎಸ್‌ಎಂಎಸ್ ಸಿಂಕ್ ಮಾಡಿ',
      'add_expense': 'ವೆಚ್ಚ ಸೇರಿಸಿ',
      'add_income': 'ಆದಾಯ ಸೇರಿಸಿ',
      'this_month': 'ಈ ತಿಂಗಳು',
      'last_month': 'ಕಳೆದ ತಿಂಗಳು',
      'all_time': 'ಎಲ್ಲಾ ಸಮಯ',
      'custom_range': 'ಕಸ್ಟಮ್ ದಿನಾಂಕ',
      'all_transactions': 'ಎಲ್ಲಾ ವಹಿವಾಟುಗಳು',
      'search_transactions': 'ವಹಿವಾಟು ಹುಡುಕಿ...',
      'filter': 'ಫಿಲ್ಟರ್',
      'income': 'ಆದಾಯ',
      'expense': 'ವೆಚ್ಚ',
      'all': 'ಎಲ್ಲಾ',
      'delete': 'ಅಳಿಸಿ',
      'save': 'ಉಳಿಸಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'khata_ledger': 'ಖಾತಾ ಲೆಡ್ಜರ್',
      'you_will_receive': 'ನಿಮಗೆ ಬರಬೇಕಾದ ಹಣ',
      'you_will_give': 'ನೀವು ನೀಡಬೇಕಾದ ಹಣ',
      'add_customer': 'ಗ್ರಾಹಕರನ್ನು ಸೇರಿಸಿ',
      'you_gave': 'ನೀವು ಕೊಟ್ಟಿದ್ದು',
      'you_got': 'ನಿಮಗೆ ಸಿಕ್ಕಿದ್ದು',
      'settle': 'ಖಾತೆ ಇತ್ಯರ್ಥ',
      'whatsapp_reminder': 'ವಾಟ್ಸಾಪ್ ಜ್ಞಾಪನೆ',
      'linked_transaction': 'ಲಿಂಕ್ ಮಾಡಿದ ವಹಿವಾಟು',
      'bill_reminders': 'ಬಿಲ್ ಜ್ಞಾಪನೆಗಳು',
      'upcoming': 'ಮುಂಬರುವ',
      'overdue': 'ಬಾಕಿ ಉಳಿದ',
      'paid': 'ಪಾವತಿಸಲಾಗಿದೆ',
      'mark_paid': 'ಪಾವತಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ',
      'language': 'ಭಾಷೆ',
      'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'export_pdf': 'ಪಿಡಿಎಫ್ ಸ್ಟೇಟ್‌ಮೆಂಟ್ ಡೌನ್‌ಲೋಡ್',
      'account_settled': 'ಖಾತೆ ಇತ್ಯರ್ಥಗೊಂಡಿದೆ',
      'no_transactions': 'ಯಾವುದೇ ವಹಿವಾಟುಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
      'no_entries': 'ಇನ್ನೂ ಯಾವುದೇ ನಮೂದುಗಳಿಲ್ಲ',
    },

    // Malayalam (മലയാളം)
    'ml': {
      'app_title': 'സ്പെൻഡ്‌വൈസ്',
      'dashboard': 'ഡാഷ്‌ബോർഡ്',
      'transactions': 'ഇടപാടുകൾ',
      'khata': 'ഖാതാബുക്ക്',
      'analytics': 'വിശകലനം',
      'reminders': 'ഓർമ്മപ്പെടുത്തലുകൾ',
      'total_balance': 'ആകെ ബാലൻസ്',
      'total_income': 'ആകെ വരുമാനം',
      'total_expense': 'ആകെ ചെലവ്',
      'today_spend': 'ഇന്നത്തെ ചെലവ്',
      'monthly_budget': 'പ്രതിമാസ ബജറ്റ്',
      'recent_transactions': 'സമീപകാല ഇടപാടുകൾ',
      'view_all': 'എല്ലാം കാണുക',
      'sync_sms': 'എസ്എംഎസ് സമന്വയിപ്പിക്കുക',
      'add_expense': 'ചെലവ് ചേർക്കുക',
      'add_income': 'വരുമാനം ചേർക്കുക',
      'this_month': 'ഈ മാസം',
      'last_month': 'കഴിഞ്ഞ മാസം',
      'all_time': 'എല്ലാ സമയത്തും',
      'custom_range': 'നിശ്ചിത തീയതി',
      'all_transactions': 'എല്ലാ ഇടപാടുകളും',
      'search_transactions': 'ഇടപാടുകൾ തിരയുക...',
      'filter': 'ഫിൽട്ടർ',
      'income': 'വരുമാനം',
      'expense': 'ചെലവ്',
      'all': 'എല്ലാം',
      'delete': 'മായ്ക്കുക',
      'save': 'സംരക്ഷിക്കുക',
      'cancel': 'റദ്ദാക്കുക',
      'khata_ledger': 'ഖാതാ ലെഡ്ജർ',
      'you_will_receive': 'ലഭിക്കാനുള്ളത്',
      'you_will_give': 'നൽകാനുള്ളത്',
      'add_customer': 'ഉപഭോക്താവിനെ ചേർക്കുക',
      'you_gave': 'കൊടുത്തത്',
      'you_got': 'ലഭിച്ചത്',
      'settle': 'അക്കൗണ്ട് തീർപ്പാക്കുക',
      'whatsapp_reminder': 'വാട്ട്‌സ്ആപ്പ് ഓർമ്മപ്പെടുത്തൽ',
      'linked_transaction': 'ബന്ധിപ്പിച്ച ഇടപാട്',
      'bill_reminders': 'ബിൽ ഓർമ്മപ്പെടുത്തലുകൾ',
      'upcoming': 'വരാനിരിക്കുന്നത്',
      'overdue': 'കാലഹരണപ്പെട്ടത്',
      'paid': 'നൽകിയത്',
      'mark_paid': 'പണമടച്ചതായി അടയാളപ്പെടുത്തുക',
      'language': 'ഭാഷ',
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'export_pdf': 'പിഡിഎഫ് സ്റ്റേറ്റ്മെന്റ്',
      'account_settled': 'അക്കൗണ്ട് പൂർണ്ണമായി തീർപ്പാക്കി',
      'no_transactions': 'ഇടപാടുകളൊന്നും കണ്ടെത്തിയില്ല',
      'no_entries': 'എൻട്രികളൊന്നും ചേർത്തിട്ടില്ല',
    },

    // Tamil (தமிழ்)
    'ta': {
      'app_title': 'ஸ்பெண்ட்வைஸ்',
      'dashboard': 'டாஷ்போர்டு',
      'transactions': 'பரிவர்த்தனைகள்',
      'khata': 'காதாபுக்',
      'analytics': 'பகுப்பாய்வு',
      'reminders': 'நினைவூட்டல்கள்',
      'total_balance': 'மொத்த இருப்பு',
      'total_income': 'மொத்த வருமானம்',
      'total_expense': 'மொத்த செலவு',
      'today_spend': 'இன்றைய செலவு',
      'monthly_budget': 'மாதாந்திர பட்ஜெட்',
      'recent_transactions': 'சமீபத்திய பரிவர்த்தனைகள்',
      'view_all': 'அனைத்தையும் பார்க்க',
      'sync_sms': 'எஸ்எம்எஸ் ஒத்திசைக்க',
      'add_expense': 'செலவு சேர்க்க',
      'add_income': 'வருமானம் சேர்க்க',
      'this_month': 'இந்த மாதம்',
      'last_month': 'கடந்த மாதம்',
      'all_time': 'எல்லா நேரமும்',
      'custom_range': 'விருப்ப வரம்பு',
      'all_transactions': 'அனைத்து பரிவர்த்தனைகள்',
      'search_transactions': 'பரிவர்த்தனைகளைத் தேடுக...',
      'filter': 'வடிகட்டி',
      'income': 'வருமானம்',
      'expense': 'செலவு',
      'all': 'அனைத்தும்',
      'delete': 'நீக்கு',
      'save': 'சேமிக்க',
      'cancel': 'ரத்து செய்',
      'khata_ledger': 'காதா லெட்ஜர்',
      'you_will_receive': 'நீங்கள் பெற வேண்டியது',
      'you_will_give': 'நீங்கள் கொடுக்க வேண்டியது',
      'add_customer': 'வாடிக்கையாளரைச் சேர்க்க',
      'you_gave': 'கொடுத்தீர்கள்',
      'you_got': 'பெற்றீர்கள்',
      'settle': 'கணக்கு தீர்க்க',
      'whatsapp_reminder': 'வாட்ஸ்அப் நினைவூட்டல்',
      'linked_transaction': 'இணைக்கப்பட்ட பரிவர்த்தனை',
      'bill_reminders': 'பில் நினைவூட்டல்கள்',
      'upcoming': 'வரவிருக்கும்',
      'overdue': 'நிலுவையில் உள்ள',
      'paid': 'செலுத்தப்பட்டது',
      'mark_paid': 'செலுத்தப்பட்டதாகக் குறிக்க',
      'language': 'மொழி',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'export_pdf': 'PDF அறிக்கை ஏற்றுமதி',
      'account_settled': 'கணக்கு தீர்க்கப்பட்டது',
      'no_transactions': 'பரிவர்த்தனைகள் எதுவும் இல்லை',
      'no_entries': 'பதிவுகள் எதுவும் இல்லை',
    },

    // Telugu (తెలుగు)
    'te': {
      'app_title': 'స్పెండ్‌వైజ్',
      'dashboard': 'డాష్‌బోర్డ్',
      'transactions': 'లావాదేవీలు',
      'khata': 'ఖాతాబుక్',
      'analytics': 'విశ్లేషణ',
      'reminders': 'రిమైండర్లు',
      'total_balance': 'మొత్తం బ్యాలెన్స్',
      'total_income': 'మొత్తం ఆదాయం',
      'total_expense': 'మొత్తం ఖర్చు',
      'today_spend': 'నేటి ఖర్చు',
      'monthly_budget': 'నెలవారీ బడ్జెట్',
      'recent_transactions': 'ఇటీవలి లావాదేవీలు',
      'view_all': 'అన్నీ చూడండి',
      'sync_sms': 'ఎస్ఎంఎస్ సమకాలీకరించు',
      'add_expense': 'ఖర్చు జోడించు',
      'add_income': 'ఆదాయం జోడించు',
      'this_month': 'ఈ నెల',
      'last_month': 'గత నెల',
      'all_time': 'మొత్తం సమయం',
      'custom_range': 'అనుకూల తేదీలు',
      'all_transactions': 'అన్ని లావాదేవీలు',
      'search_transactions': 'లావాదేవీలను వెతకండి...',
      'filter': 'ఫిల్టర్',
      'income': 'ఆదాయం',
      'expense': 'ఖర్చు',
      'all': 'అన్నీ',
      'delete': 'తొలగించు',
      'save': 'సేవ్ చేయి',
      'cancel': 'రద్దు చేయి',
      'khata_ledger': 'ఖాతా లెడ్జర్',
      'you_will_receive': 'మీకు రావాల్సినవి',
      'you_will_give': 'మీరు ఇవ్వాల్సినవి',
      'add_customer': 'కస్టమర్‌ను జోడించు',
      'you_gave': 'మీరు ఇచ్చారు',
      'you_got': 'మీకు వచ్చాయి',
      'settle': 'ఖాతా సరిచేయి',
      'whatsapp_reminder': 'వాట్సాప్ రిమైండర్',
      'linked_transaction': 'లింక్ చేయబడిన లావాదేవీ',
      'bill_reminders': 'బిల్ రిమైండర్లు',
      'upcoming': 'రాబోయేవి',
      'overdue': 'గడువు ముగిసినవి',
      'paid': 'చెల్లించినవి',
      'mark_paid': 'చెల్లించినట్లు గుర్తించు',
      'language': 'భాష',
      'select_language': 'భాషను ఎంచుకోండి',
      'export_pdf': 'పిడిఎఫ్ స్టేట్‌మెంట్ డౌన్‌లోడ్',
      'account_settled': 'ఖాతా పూర్తయింది',
      'no_transactions': 'లావాదేవీలేవీ కనుగొనబడలేదు',
      'no_entries': 'ఇంకా ఎలాంటి రికార్డులు లేవు',
    },

    // Marathi (मराठी)
    'mr': {
      'app_title': 'स्पेंडवाईज',
      'dashboard': 'डॅशबोर्ड',
      'transactions': 'व्यवहार',
      'khata': 'खातावही',
      'analytics': 'विश्लेषण',
      'reminders': 'आठवणी',
      'total_balance': 'एकूण शिल्लक',
      'total_income': 'एकूण उत्पन्न',
      'total_expense': 'एकूण खर्च',
      'today_spend': 'आजचा खर्च',
      'monthly_budget': 'मासिक बजेट',
      'recent_transactions': 'अलीकडील व्यवहार',
      'view_all': 'सर्व पहा',
      'sync_sms': 'एसएमएस सिंक करा',
      'add_expense': 'खर्च जोडा',
      'add_income': 'उत्पन्न जोडा',
      'this_month': 'या महिन्यात',
      'last_month': 'मागील महिन्यात',
      'all_time': 'सर्व वेळ',
      'custom_range': 'सानुकूल कालावधी',
      'all_transactions': 'सर्व व्यवहार',
      'search_transactions': 'व्यवहार शोधा...',
      'filter': 'फिल्टर',
      'income': 'उत्पन्न',
      'expense': 'खर्च',
      'all': 'सर्व',
      'delete': 'हटवा',
      'save': 'जतन करा',
      'cancel': 'रद्द करा',
      'khata_ledger': 'खाते लेजर',
      'you_will_receive': 'तुम्हाला मिळतील',
      'you_will_give': 'तुम्हाला द्यायचे आहेत',
      'add_customer': 'ग्राहक / मित्र जोडा',
      'you_gave': 'दिले (Gave)',
      'you_got': 'मिळाले (Got)',
      'settle': 'खाते चुकता करा',
      'whatsapp_reminder': 'व्हॉट्सअॅप स्मरणपत्र',
      'linked_transaction': 'जोडलेला व्यवहार',
      'bill_reminders': 'बिल स्मरणपत्रे',
      'upcoming': 'आगामी',
      'overdue': 'थकबाकी',
      'paid': 'भरले',
      'mark_paid': 'भरले म्हणून चिन्हांकित करा',
      'language': 'भाषा',
      'select_language': 'भाषा निवडा',
      'export_pdf': 'पीडीएफ स्टेटमेंट डाउनलोड',
      'account_settled': 'खाते चुकता झाले आहे',
      'no_transactions': 'कोणतेही व्यवहार आढळले नाहीत',
      'no_entries': 'अद्याप कोणत्याही नोंदी नाहीत',
    },

    // Gujarati (ગુજરાતી)
    'gu': {
      'app_title': 'સ્પેન્ડવાઇઝ',
      'dashboard': 'ડેશબોર્ડ',
      'transactions': 'વ્યવહારો',
      'khata': 'ખાતાબહી',
      'analytics': 'વિશ્લેષણ',
      'reminders': 'રિમાઇન્ડર્સ',
      'total_balance': 'કુલ બેલેન્સ',
      'total_income': 'કુલ આવક',
      'total_expense': 'કુલ ખર્ચ',
      'today_spend': 'આજનો ખર્ચ',
      'monthly_budget': 'માસિક બજેટ',
      'recent_transactions': 'તાજેતરના વ્યવહારો',
      'view_all': 'બધું જુઓ',
      'sync_sms': 'એસએમએસ સિંક કરો',
      'add_expense': 'ખર્ચ ઉમેરો',
      'add_income': 'આવક ઉમેરો',
      'this_month': 'આ મહિને',
      'last_month': 'ગયા મહિને',
      'all_time': 'તમામ સમય',
      'custom_range': 'કસ્ટમ તારીખ',
      'all_transactions': 'તમામ વ્યવહારો',
      'search_transactions': 'વ્યવહારો શોધો...',
      'filter': 'ફિલ્ટર',
      'income': 'આવક',
      'expense': 'ખર્ચ',
      'all': 'બધા',
      'delete': 'કાઢી નાખો',
      'save': 'સાચવો',
      'cancel': 'રદ કરો',
      'khata_ledger': 'ખાતા લેજર',
      'you_will_receive': 'તમને મળશે',
      'you_will_give': 'તમારે આપવાના છે',
      'add_customer': 'ગ્રાહક ઉમેરો',
      'you_gave': 'આપ્યા (Gave)',
      'you_got': 'મળ્યા (Got)',
      'settle': 'ખાતું ચૂકતે કરો',
      'whatsapp_reminder': 'વોટ્સએપ રિમાઇન્ડર',
      'linked_transaction': 'જોડાયેલ વ્યવહાર',
      'bill_reminders': 'બિલ રિમાઇન્ડર્સ',
      'upcoming': 'આગામી',
      'overdue': 'બાકી',
      'paid': 'ચૂકવેલ',
      'mark_paid': 'ચૂકવેલ તરીકે ચિહ્નિત કરો',
      'language': 'ભાષા',
      'select_language': 'ભાષા પસંદ કરો',
      'export_pdf': 'પીડીએફ સ્ટેટમેન્ટ ડાઉનલોડ',
      'account_settled': 'ખાતું પૂરું ચૂકવાઈ ગયું છે',
      'no_transactions': 'કોઈ વ્યવહારો મળ્યા નથી',
      'no_entries': 'હજી કોઈ એન્ટ્રી નથી',
    },

    // Punjabi (ਪੰਜਾਬੀ)
    'pa': {
      'app_title': 'ਸਪੈਂਡਵਾਈਜ਼',
      'dashboard': 'ਡੈਸ਼ਬੋਰਡ',
      'transactions': 'ਲੈਣ-ਦੇਣ',
      'khata': 'ਖਾਤਾਬਹੀ',
      'analytics': 'ਵਿਸ਼ਲੇਸ਼ਣ',
      'reminders': 'ਯਾਦ-ਦਹਾਨੀਆਂ',
      'total_balance': 'ਕੁੱਲ ਬਕਾਇਆ',
      'total_income': 'ਕੁੱਲ ਆਮਦਨ',
      'total_expense': 'ਕੁੱਲ ਖ਼ਰਚਾ',
      'today_spend': 'ਅੱਜ ਦਾ ਖ਼ਰਚਾ',
      'monthly_budget': 'ਮਹੀਨਾਵਾਰ ਬਜਟ',
      'recent_transactions': 'ਤਾਜ਼ਾ ਲੈਣ-ਦੇਣ',
      'view_all': 'ਸਾਰੇ ਵੇਖੋ',
      'sync_sms': 'SMS ਸਿੰਕ ਕਰੋ',
      'add_expense': 'ਖ਼ਰਚਾ ਜੋੜੋ',
      'add_income': 'ਆਮਦਨ ਜੋੜੋ',
      'this_month': 'ਇਸ ਮਹੀਨੇ',
      'last_month': 'ਪਿਛਲੇ ਮਹੀਨੇ',
      'all_time': 'ਸਾਰਾ ਸਮਾਂ',
      'custom_range': 'ਕਸਟਮ ਮਿਤੀ',
      'all_transactions': 'ਸਾਰੇ ਲੈਣ-ਦੇਣ',
      'search_transactions': 'ਲੈਣ-ਦੇਣ ਖੋਜੋ...',
      'filter': 'ਫਿਲਟਰ',
      'income': 'ਆਮਦਨ',
      'expense': 'ਖ਼ਰਚਾ',
      'all': 'ਸਾਰੇ',
      'delete': 'ਮਿਟਾਓ',
      'save': 'ਸੰਭਾਲੋ',
      'cancel': 'ਰੱਦ ਕਰੋ',
      'khata_ledger': 'ਖਾਤਾ ਲੈਜ਼ਰ',
      'you_will_receive': 'ਤੁਹਾਨੂੰ ਮਿਲਣਗੇ',
      'you_will_give': 'ਤੁਸੀਂ ਦੇਣੇ ਹਨ',
      'add_customer': 'ਗਾਹਕ / ਮਿੱਤਰ ਜੋੜੋ',
      'you_gave': 'ਦਿੱਤੇ',
      'you_got': 'ਮਿਲੇ',
      'settle': 'ਖਾਤਾ ਚੁਕਤਾ ਕਰੋ',
      'whatsapp_reminder': 'ਵਟਸਐਪ ਯਾਦ-ਦਹਾਨੀ',
      'linked_transaction': 'ਜੁੜਿਆ ਲੈਣ-ਦੇਣ',
      'bill_reminders': 'ਬਿੱਲ ਯਾਦ-ਦਹਾਨੀਆਂ',
      'upcoming': 'ਆਉਣ ਵਾਲੇ',
      'overdue': 'ਬਕਾਇਆ',
      'paid': 'ਅਦਾ ਕੀਤਾ',
      'mark_paid': 'ਅਦਾ ਕੀਤਾ ਗਿਆ ਚਿੰਨ੍ਹਿਤ ਕਰੋ',
      'language': 'ਭਾਸ਼ਾ',
      'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'export_pdf': 'PDF ਸਟੇਟਮੈਂਟ ਡਾਊਨਲੋਡ',
      'account_settled': 'ਖਾਤਾ ਚੁਕਤਾ ਹੋ ਗਿਆ ਹੈ',
      'no_transactions': 'ਕੋਈ ਲੈਣ-ਦੇਣ ਨਹੀਂ ਮਿਲਿਆ',
      'no_entries': 'ਅਜੇ ਕੋਈ ਐਂਟਰੀ ਨਹੀਂ',
    },
  };

  String translate(String key) {
    final langCode = locale.languageCode;
    return _localizedValues[langCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'hi', 'bn', 'ur', 'ar', 'kn', 'ml', 'ta', 'te', 'mr', 'gu', 'pa']
        .contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

/// Helper extension on BuildContext for effortless translation: context.tr('key')
extension LocalizationContext on BuildContext {
  String tr(String key) => AppLocalizations.of(this).translate(key);
}
